#!/usr/bin/env bash

APP="pfa" # name of your release

BUILD_HOST="107.170.71.198" # host where to build the release
BUILD_USER="deploy" # local user at build host
BUILD_AT="/git/pfa.nyc/builds" # build directory on build host
RELEASE_DIR="/git/pfa.nyc/builds/rel/pfa.nyc"

USING_DISTILLERY=true

# STAGING_HOSTS="server ip / hostname" # staging / test hosts separated by space
# STAGING_USER="git" # local user at staging hosts
# TEST_AT="/test/my_awesome_app" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="107.170.71.198" # deploy / production hosts separated by space
PRODUCTION_USER="deploy" # local user at deploy hosts
DELIVER_TO="/opt/pfa.nyc" # deploy directory on production hosts
